# Laboratuvar

## Eski Analitikler, Yeni Preanalitikler


::: {.panel-tabset}

### Zorluklar

Content for `Tab A`

### Kolaylıklar

Content for `Tab B`

:::



## Barkod, Karekod, Datamatrix



::: {.panel-tabset}

### Zorluklar

Content for `Tab A`

### Kolaylıklar

Content for `Tab B`

:::



## Makroskopi


::: {.panel-tabset}

### Zorluklar

Content for `Tab A`

### Kolaylıklar

Content for `Tab B`

:::


## Gömme {auto-animate="true"}



::: {.panel-tabset}

### Zorluklar

Content for `Tab A`

### Kolaylıklar

Content for `Tab B`

:::


Düzenli gömme

Bıçağa göre açılı gömme vs düz gömme 


## Kesit {auto-animate="true"}

Kesit kalınlığı

Kesitin merkezde olması

Katlantılar


## Kapama



::: {.panel-tabset}

### Zorluklar

Content for `Tab A`

### Kolaylıklar

Content for `Tab B`

:::


## Temizlik



::: {.panel-tabset}

### Zorluklar

Content for `Tab A`

### Kolaylıklar

Content for `Tab B`

:::


## Doku sanılan artefaktlar


::: {.panel-tabset}

### Zorluklar

Content for `Tab A`

### Kolaylıklar

Content for `Tab B`

:::


## Odaklanma sorunu


::: {.panel-tabset}

### Zorluklar

Content for `Tab A`

### Kolaylıklar

Content for `Tab B`

:::


## Hastane BYS, Laboratuvar BYS



::: {.panel-tabset}

### Zorluklar

Content for `Tab A`

### Kolaylıklar

Content for `Tab B`

:::


## PACS, Depo, Arşiv



::: {.panel-tabset}

### Zorluklar

Content for `Tab A`

### Kolaylıklar

Content for `Tab B`

:::


## İş Akışı



::: {.panel-tabset}

### Zorluklar

Content for `Tab A`

### Kolaylıklar

Content for `Tab B`

:::



