flowchart TB
Frozen[Frozen] --> Ameliyathane[Ameliyathane]
Ameliyathane[Ameliyathane] --> Transfer[Hastane Transfer]
HastaBasi[Hasta Başı] --> Transfer[Hastane Transfer]
Poliklinik[Poliklinik] --> Transfer[Hastane Transfer]
Transfer[Hastane Transfer] --> PatolojiKabul{Patoloji Kabul}