flowchart TB
style PatolojiKabul fill:#F7DC6F, font-size:10px
style Makroskopi fill:#F7DC6F
style Sitoloji fill:#F7DC6F
style DokuTakip fill:#F7DC6F
style Gomme fill:#F7DC6F
style Kesit fill:#F7DC6F
style Tarama fill:#82E0AA
style HE fill:#F7DC6F
style HK fill:#F7DC6F
style IHK fill:#F7DC6F
style ISH fill:#F7DC6F
Frozen[Frozen] --> Ameliyathane[Ameliyathane]
Ameliyathane[Ameliyathane] --> Transfer[Hastane Transfer]
HastaBasi[Hasta Başı] --> Transfer[Hastane Transfer]
Poliklinik[Poliklinik] --> Transfer[Hastane Transfer]
Transfer[Hastane Transfer] --> PatolojiKabul{Patoloji Kabul}
PatolojiKabul{Patoloji Kabul} --> Makroskopi[Makroskopi]
PatolojiKabul{Patoloji Kabul} --> Sitoloji[Sitoloji]
Makroskopi[Makroskopi] --> DokuTakip[Doku Takip]
Sitoloji[Sitoloji] --> DokuTakip[Doku Takip]
DokuTakip[Doku Takip] --> Gomme[Gömme]
Gomme[Gömme] --> Kesit{Kesit}
Kesit{Kesit} -.-HE-.-> Tarama[Dijital Tarama]
Kesit{Kesit} -.- HK-.-> Tarama[Dijital Tarama]
Kesit{Kesit} -.- IHK-.-> Tarama[Dijital Tarama]
Kesit{Kesit} -.- ISH-.-> Tarama[Dijital Tarama]
Sitoloji[Sitoloji] --> Tarama[Dijital Tarama]